kind: Service                             
apiVersion: v1
metadata:
  name: krupangbuddhdev
  labels:
    app: krupangbuddhdev
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: krupangbuddhdev                    
  type: LoadBalancer                   
